version: '3.4'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server

  assignmentapi:
    image: ${DOCKER_REGISTRY-}assignmentapi
    build:
      context: ./../AssignementAPI
      dockerfile: Assignments.API/Dockerfile
  
  front:
    image: ${DOCKER_REGISTRY-}front
    build:
      context: ./../angular-13-web-mbds
      dockerfile: Dockerfile
    links:
        - assignmentapi