version: '3.4'

services:
  apirobot:
    environment:
      - ASPNETCORE_URLS=https://+:8001;http://+:8000
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=0099669
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificat.pfx
    ports:
      - "8000:8000"
      - "8001:8001"
      - "1883:1883"
      - "11000:11000"
      - "8884:8884"
    volumes:
      - ../Certificates/self/https:/https/

  frontrobot:
    ports:
      - "443:443"
    volumes:
      - ../Certificates/self:/https/ 