version: '3.4'

services:

  sqlserver:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Azerty*00
      - MSSQL_AGENT_ENABLED=True
    ports:
      - "1433:1433"
    volumes:
      - ./database_mssql:/var/opt/mssql/data
    restart: always

  assignmentapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - "sqlserver"