version: '3.4'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver

  assignments.api:
    image: ${DOCKER_REGISTRY-}assignmentsapi
    build:
      context: .
      dockerfile: Assignments.API/Dockerfile
