version: '3.4'

services:

  sqlserver:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Azerty*00
      - MSSQL_AGENT_ENABLED=True
    ports:
      - "1433:1433"
    volumes:
      - ./database_mssql:/var/opt/mssql/data
    restart: always

  assignments.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8001;http://+:8000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=0099669
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificat.pfx
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ../Certificates/self/https:/https/
    depends_on:
      - "sqlserver"