version: '3.4'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver

  assignmentapi:
    image: ${DOCKER_REGISTRY-}assignmentapi
    build:
      context: .
      dockerfile: Assignments.API/Dockerfile